on: 
    push : 
        branches: 
            - main
name: 🚀 Deploy laravel CI/CD on push
jobs:
  laravel-deploy:
    name: 🎉 Deploy Laravel CI/CD
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Use Node.js and Composer cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.composer
        key: ${{ runner.os }}-build-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install Dependencies and Build Assets
      run: |
        npm install
        npm run build

    - name: Check if .env exists
      run: |
        php -r 'echo file_exists(".env") ? "Exists" : "Not exists";'
      
       

    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: www.developry.my.id
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /staging.developry.my.id/
